# Generated by Django 4.2.4 on 2023-12-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0009_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
